spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&amp&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: each
    password: each123.

